-- Add new values to StartupStage enum
ALTER TYPE "StartupStage" ADD VALUE IF NOT EXISTS 'PRE_SERIES_B';
ALTER TYPE "StartupStage" ADD VALUE IF NOT EXISTS 'PRE_SERIES_C';
ALTER TYPE "StartupStage" ADD VALUE IF NOT EXISTS 'PRE_SERIES_D';
ALTER TYPE "StartupStage" ADD VALUE IF NOT EXISTS 'SERIES_D';
ALTER TYPE "StartupStage" ADD VALUE IF NOT EXISTS 'SERIES_E';
ALTER TYPE "StartupStage" ADD VALUE IF NOT EXISTS 'SERIES_F';
ALTER TYPE "StartupStage" ADD VALUE IF NOT EXISTS 'SERIES_G';
ALTER TYPE "StartupStage" ADD VALUE IF NOT EXISTS 'SERIES_I';
ALTER TYPE "StartupStage" ADD VALUE IF NOT EXISTS 'SERIES_J';
