-- Complete seed data for India AI section
-- This script adds comprehensive data for all India AI tables

-- Clear existing data
DELETE FROM "AIResearcher";
DELETE FROM "IndianAITool";
DELETE FROM "FeaturedFounder";
DELETE FROM "PolicyUpdate";
DELETE FROM "GovernmentScheme";

-- Insert Government Schemes (5 schemes)
INSERT INTO "GovernmentScheme" (id, name, "shortName", "fundingAmount", eligibility, "applicationDeadline", status, "applyLink", description, benefits, category, state, "displayOrder", "isActive", "createdAt", "updatedAt")
VALUES 
('scheme-1', 'IndiaAI Mission', 'IndiaAI', '₹10,372 Cr', ARRAY['AI startups registered in India', 'Research institutions', 'Computing infrastructure providers', 'AI dataset creators'], 'Rolling basis', 'Open', 'https://indiaai.gov.in', 'National program to democratize AI computing, innovation, and safe AI deployment', ARRAY['Access to AI compute infrastructure', 'Dataset creation grants', 'Application development support', 'Safe & Trusted AI framework'], 'Central', NULL, 0, true, NOW(), NOW()),
('scheme-2', 'Startup India Seed Fund Scheme', 'SISFS', 'Up to ₹50L', ARRAY['DPIIT recognized startups', 'Incorporated < 2 years ago', 'Working on innovative products/services', 'Not received > ₹10L funding'], 'Rolling basis', 'Open', 'https://www.startupindia.gov.in/content/sih/en/startup-scheme/seed-fund-scheme.html', 'Seed funding to startups for proof of concept, prototype development, product trials, and market entry', ARRAY['Seed funding up to ₹20L', 'Validation/prototype: ₹50L', 'Mentorship support', 'No equity dilution'], 'Central', NULL, 1, true, NOW(), NOW()),
('scheme-3', 'Karnataka AI Policy', 'Karnataka AI', '₹500 Cr fund', ARRAY['AI startups in Karnataka', 'Setting up AI CoEs', 'AI research projects', 'Skilling initiatives'], 'Rolling basis', 'Open', 'https://itbt.karnataka.gov.in', 'State policy to position Karnataka as India''s AI hub with dedicated funding and infrastructure', ARRAY['Access to AI compute', 'Office space subsidies', 'Talent pool access', 'Regulatory sandbox'], 'State', 'Karnataka', 2, true, NOW(), NOW()),
('scheme-4', 'Tamil Nadu AI Policy', 'TN AI', '₹1,000 Cr investment', ARRAY['AI startups in Tamil Nadu', 'AI research institutions', 'Manufacturing AI solutions', 'AI for social good'], 'Rolling basis', 'Open', 'https://tnega.tn.gov.in', 'Comprehensive AI policy to attract ₹1,000 Cr investment and create 20,000 jobs', ARRAY['Capital subsidy up to 50%', 'Land at concessional rates', 'Power tariff subsidies', 'Fast-track approvals'], 'State', 'Tamil Nadu', 3, true, NOW(), NOW()),
('scheme-5', 'SAMRIDH Scheme', 'SAMRIDH', 'Up to ₹1 Cr', ARRAY['Healthcare tech startups', 'Post-seed stage (raised ₹50L+)', 'Scalable business model', 'Impact on healthcare delivery'], 'Cohort-based', 'Open', 'https://www.startupindia.gov.in/content/sih/en/startup-scheme/samridh.html', 'Accelerator program for healthcare startups to scale and achieve market access', ARRAY['Soft loan up to ₹1 Cr', 'Mentorship from industry experts', 'Market access support', 'Pilot opportunities with hospitals'], 'Central', NULL, 4, true, NOW(), NOW());

-- Insert Policy Updates (6 updates)
INSERT INTO "PolicyUpdate" (id, title, source, date, excerpt, link, category, impact, "displayOrder", "isActive", "createdAt", "updatedAt")
VALUES
('policy-1', 'MeitY Releases Draft AI Ethics Framework for Public Consultation', 'MeitY', '2026-05-03', 'Ministry of Electronics and IT has released a comprehensive AI ethics framework covering fairness, transparency, accountability, and privacy. Public comments invited until June 15, 2026.', 'https://meity.gov.in', 'Policy', 'High', 0, true, NOW(), NOW()),
('policy-2', 'NITI Aayog Announces ₹500 Cr AI Research Fund for IITs', 'NITI Aayog', '2026-05-01', 'National Institution for Transforming India allocates ₹500 crore for AI research across 23 IITs. Focus areas include healthcare AI, agricultural AI, and climate modeling.', 'https://niti.gov.in', 'Funding', 'High', 1, true, NOW(), NOW()),
('policy-3', 'Digital Personal Data Protection Act: AI-Specific Guidelines Released', 'Data Protection Board', '2026-04-28', 'Data Protection Board of India issues guidelines for AI systems processing personal data. Mandates algorithmic transparency and user consent for automated decision-making.', 'https://dpb.gov.in', 'Regulation', 'High', 2, true, NOW(), NOW()),
('policy-4', 'AI Safety Standards Committee Publishes Testing Framework', 'Bureau of Indian Standards', '2026-04-25', 'Bureau of Indian Standards releases AI safety testing framework covering robustness, security, and bias evaluation. Voluntary compliance for now, mandatory from 2027.', 'https://bis.gov.in', 'Standards', 'Medium', 3, true, NOW(), NOW()),
('policy-5', 'Supreme Court Ruling: AI-Generated Evidence Admissibility Guidelines', 'Supreme Court of India', '2026-04-20', 'Landmark judgment establishes criteria for admitting AI-generated evidence in courts. Requires explainability, audit trails, and expert testimony on model reliability.', '#', 'Legal', 'High', 4, true, NOW(), NOW()),
('policy-6', 'MeitY Launches AI Compute Access Program for Startups', 'MeitY', '2026-04-18', 'New program provides subsidized access to GPU clusters for AI startups. Applications open for companies with < ₹10 Cr revenue. Up to 1000 GPU hours per quarter.', 'https://meity.gov.in', 'Policy', 'High', 5, true, NOW(), NOW());

-- Insert AI Researchers (5 researchers)
INSERT INTO "AIResearcher" (id, name, university, position, "photoUrl", bio, "researchAreas", "notablePapers", "linkedinUrl", "googleScholarUrl", citations, "hIndex", "displayOrder", "isActive", "createdAt", "updatedAt")
VALUES
('researcher-1', 'Dr. Rajesh Kumar', 'IIT Delhi', 'Professor of Computer Science', NULL, 'Leading researcher in Natural Language Processing and Computer Vision with 15+ years of experience. Pioneer in developing transformer models for Indian languages.', ARRAY['Natural Language Processing', 'Computer Vision', 'Deep Learning', 'Multilingual AI'], ARRAY['Transformer Models for Indian Languages (2024)', 'Vision Systems for Agricultural AI (2023)', 'Low-Resource Language Processing (2022)'], 'https://linkedin.com/in/rajeshkumar', 'https://scholar.google.com/rajeshkumar', 5000, 45, 0, true, NOW(), NOW()),
('researcher-2', 'Dr. Priya Sharma', 'IIT Bombay', 'Associate Professor', NULL, 'Expert in Machine Learning and AI Ethics, focusing on responsible AI development and fairness in algorithmic systems. Advisor to multiple AI startups.', ARRAY['Machine Learning', 'AI Ethics', 'Fairness in AI', 'Explainable AI'], ARRAY['Bias Detection in ML Models (2025)', 'Ethical AI Framework for India (2024)', 'Fairness Metrics for Classification (2023)'], 'https://linkedin.com/in/priyasharma', 'https://scholar.google.com/priyasharma', 3500, 38, 1, true, NOW(), NOW()),
('researcher-3', 'Dr. Amit Patel', 'IISc Bangalore', 'Professor', NULL, 'Pioneering work in Reinforcement Learning and Robotics applications. Leading the AI for Manufacturing initiative at IISc.', ARRAY['Reinforcement Learning', 'Robotics', 'Autonomous Systems', 'Industrial AI'], ARRAY['RL for Industrial Automation (2025)', 'Multi-Agent Systems in Manufacturing (2024)', 'Safe Reinforcement Learning (2023)'], 'https://linkedin.com/in/amitpatel', 'https://scholar.google.com/amitpatel', 4200, 42, 2, true, NOW(), NOW()),
('researcher-4', 'Dr. Meera Reddy', 'IIT Madras', 'Assistant Professor', NULL, 'Specializing in Healthcare AI and Medical Imaging. Developed AI systems for early disease detection deployed in 50+ hospitals across India.', ARRAY['Healthcare AI', 'Medical Imaging', 'Deep Learning', 'Computer Vision'], ARRAY['AI for Diabetic Retinopathy Detection (2025)', 'Chest X-Ray Analysis using CNNs (2024)', 'Federated Learning in Healthcare (2023)'], 'https://linkedin.com/in/meerareddy', 'https://scholar.google.com/meerareddy', 2800, 32, 3, true, NOW(), NOW()),
('researcher-5', 'Dr. Arjun Verma', 'IIT Kharagpur', 'Professor', NULL, 'Expert in Speech Recognition and Audio Processing for Indian languages. Co-founder of two successful AI startups.', ARRAY['Speech Recognition', 'Audio Processing', 'Signal Processing', 'Acoustic Modeling'], ARRAY['Speech Recognition for Indian Languages (2024)', 'Low-Latency ASR Systems (2023)', 'Noise-Robust Speech Processing (2022)'], 'https://linkedin.com/in/arjunverma', 'https://scholar.google.com/arjunverma', 3200, 36, 4, true, NOW(), NOW());

-- Insert Indian AI Tools (5 tools)
INSERT INTO "IndianAITool" (id, name, slug, tagline, description, "logoUrl", "websiteUrl", category, "foundedYear", "fundingStatus", "totalFunding", headquarters, "teamSize", features, "useCases", "isFeatured", "displayOrder", "isActive", "createdAt", "updatedAt")
VALUES
('tool-1', 'Sarvam AI', 'sarvam-ai', 'India''s first full-stack AI platform', 'Building foundation models and AI infrastructure specifically designed for Indian languages and use cases. Offers multilingual LLMs, speech-to-text, and text-to-speech capabilities.', NULL, 'https://sarvam.ai', 'LLM/Foundation Models', 2023, 'Series A', '$41M', 'Bangalore, Karnataka', '50-100', ARRAY['Multilingual LLM (10+ Indian languages)', 'Speech-to-text API', 'Text-to-speech synthesis', 'Real-time translation', 'Custom model fine-tuning'], ARRAY['Customer support automation', 'Content creation in regional languages', 'Voice assistants for Indian markets', 'Government service digitization'], true, 0, true, NOW(), NOW()),
('tool-2', 'Krutrim AI', 'krutrim-ai', 'India''s own AI', 'Building AI models trained on Indian data for Indian languages and cultural contexts. First Indian AI unicorn focused on indigenous AI development.', NULL, 'https://krutrim.ai', 'LLM/Foundation Models', 2023, 'Seed', '$50M', 'Bangalore, Karnataka', '100-200', ARRAY['Indic language support (20+ languages)', 'Cultural context understanding', 'Local data training', 'API access', 'Enterprise solutions'], ARRAY['Education technology', 'Healthcare diagnostics', 'Government services', 'Financial services'], true, 1, true, NOW(), NOW()),
('tool-3', 'Yellow.ai', 'yellow-ai', 'Enterprise conversational AI platform', 'AI-powered customer service automation platform serving 1000+ enterprises globally. Specializes in omnichannel customer engagement.', NULL, 'https://yellow.ai', 'Conversational AI', 2016, 'Series C', '$102M', 'Bangalore, Karnataka', '500+', ARRAY['Omnichannel support (chat, voice, email)', 'Voice bots with NLU', 'Chat automation', 'Analytics dashboard', 'CRM integrations', '100+ language support'], ARRAY['Customer support automation', 'Sales automation', 'HR automation', 'IT helpdesk'], false, 2, true, NOW(), NOW()),
('tool-4', 'Haptik', 'haptik', 'Conversational AI for enterprises', 'Leading conversational AI platform acquired by Reliance Jio. Powers customer engagement for major Indian brands.', NULL, 'https://haptik.ai', 'Conversational AI', 2013, 'Acquired', '$100M+', 'Mumbai, Maharashtra', '300+', ARRAY['Intelligent virtual assistants', 'WhatsApp Business API', 'Voice AI', 'Analytics & insights', 'Multi-language support'], ARRAY['E-commerce customer support', 'Banking & finance', 'Travel & hospitality', 'Retail automation'], false, 3, true, NOW(), NOW()),
('tool-5', 'Niramai', 'niramai', 'AI for breast cancer screening', 'Revolutionary AI-powered breast cancer screening solution using thermal imaging. Non-invasive, radiation-free, and affordable.', NULL, 'https://niramai.com', 'Healthcare AI', 2016, 'Series A', '$10M', 'Bangalore, Karnataka', '50-100', ARRAY['Thermal imaging analysis', 'AI-powered diagnosis', 'Cloud-based reporting', 'Mobile screening units', 'Privacy-preserving'], ARRAY['Early breast cancer detection', 'Rural healthcare screening', 'Corporate health programs', 'Hospital integration'], true, 4, true, NOW(), NOW());

-- Insert Featured Founders (5 founders)
INSERT INTO "FeaturedFounder" (id, name, "startupName", "startupSlug", "photoUrl", bio, achievement, "fundingRaised", category, "linkedinUrl", "twitterUrl", "storyUrl", "displayOrder", "isActive", "createdAt", "updatedAt")
VALUES
('founder-1', 'Vivek Raghavan', 'Sarvam AI', 'sarvam-ai', NULL, 'Former VP of Engineering at Flipkart, now building India''s first full-stack AI platform. IIT Madras alumnus with 15+ years in tech.', 'Raised $41M Series A to build foundation models for Indian languages. Previously led AI initiatives at Flipkart serving 300M+ users.', '$41M', 'Rising Star', 'https://linkedin.com/in/vivekraghavan', 'https://twitter.com/vivekraghavan', NULL, 0, true, NOW(), NOW()),
('founder-2', 'Bhavish Aggarwal', 'Krutrim AI', 'krutrim-ai', NULL, 'Founder of Ola Cabs, now building India''s own AI. IIT Bombay alumnus and one of India''s most successful entrepreneurs.', 'Launched India''s first indigenous AI model with $50M funding. Built Ola into a $6B+ company before pivoting to AI.', '$50M', 'Hall of Fame', 'https://linkedin.com/in/bhavishaggarwal', 'https://twitter.com/bhash', NULL, 1, true, NOW(), NOW()),
('founder-3', 'Raghu Ravinutala', 'Yellow.ai', 'yellow-ai', NULL, 'Serial entrepreneur and AI visionary. Previously co-founded multiple successful startups. Stanford alumnus.', 'Scaled Yellow.ai to $102M in funding and 500+ employees. Serving 1000+ enterprise customers globally including Domino''s, Sephora, and Hyundai.', '$102M', 'Featured', 'https://linkedin.com/in/raghuravinutala', 'https://twitter.com/raghur', NULL, 2, true, NOW(), NOW()),
('founder-4', 'Aakrit Vaish', 'Haptik', 'haptik', NULL, 'Co-founder of Haptik, acquired by Reliance Jio. IIT Roorkee alumnus. Forbes 30 Under 30 Asia.', 'Built Haptik from scratch to acquisition by Reliance Jio for $100M+. Now leading conversational AI for Jio''s 400M+ users.', '$100M+', 'Hall of Fame', 'https://linkedin.com/in/aakritvaish', 'https://twitter.com/aakritvaish', NULL, 3, true, NOW(), NOW()),
('founder-5', 'Geetha Manjunath', 'Niramai', 'niramai', NULL, 'PhD from IISc Bangalore. Former scientist at Xerox Research. Pioneer in AI for healthcare in India.', 'Developed AI-powered breast cancer screening solution deployed in 100+ centers. Raised $10M to make cancer screening accessible and affordable.', '$10M', 'Rising Star', 'https://linkedin.com/in/geethamanjunath', 'https://twitter.com/geethamanjunath', NULL, 4, true, NOW(), NOW());
