/**
 * Utility for securely uploading files directly to Cloudflare R2
 * using pre-signed URLs generated by the AIStartupImpact API.
 */

const API_BASE = process.env.NEXT_PUBLIC_API_URL || 'http://localhost:4000/v1';

export async function uploadToStorage(file: File): Promise<string> {
  try {
    // 1. Request the pre-signed URL from our backend
    const presignRes = await fetch(`${API_BASE}/upload/presign`, {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
      },
      body: JSON.stringify({
        filename: file.name,
        contentType: file.type,
      }),
    });

    if (!presignRes.ok) {
      const errorData = await presignRes.json();
      throw new Error(errorData.error || 'Failed to get upload URL');
    }

    const { presignedUrl, finalUrl } = await presignRes.json();

    // 2. Upload the file directly to Cloudflare R2 using the presigned URL
    const uploadRes = await fetch(presignedUrl, {
      method: 'PUT',
      headers: {
        'Content-Type': file.type,
      },
      body: file,
    });

    if (!uploadRes.ok) {
      throw new Error(`Cloudflare R2 returned ${uploadRes.status}`);
    }

    // 3. Return the final public URL
    return finalUrl;
  } catch (error) {
    console.error('Upload Error:', error);
    throw error;
  }
}
